development:
  adapter: postgresql
  encoding: unicode
  database: anagrammatist_development
  host: localhost
  pool: 50
  username: user
  database: app-dev

test:
  adapter: postgresql
  encoding: unicode
  database: anagrammatist_test
  host: localhost
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  database: <%= ENV['DATABASE_NAME'] || 'sinatra' %>
  username: <%= ENV['DATABASE_USER'] || 'sinatra' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'sinatra' %>
